#!/usr/bin/env python

#//////////////////////////////////////////////////////////////////////////
#//
#// Copyright Verizon 2017
#//
#// Prognosis:  Analyze a repository for dangerous content
#// Date:       3/13/17
#// Authors:    David Andrews
#//
#//////////////////////////////////////////////////////////////////////////

# this script receives in a provided location, or cwd, and runs the regexes provided by
# gitrob_signatures.json, plus additional ones that are "part": "contents" to look for bad things

import json
import re
import sys
import os
import argparse

signatures = [
  {
      "part": "contents",
      "type": "regex",
      "pattern": "(host|host_?name|host_?addr|ip|ip_?addr|ip_?address) ?= ?['\"](1(?!(27|0|92)\\.)|[2-9]+)",
      "caption": "non RFC-1918 IP address",
      "description": None
  },
  {
      "part": "contents",
      "type": "regex",
      "pattern": "(password|passwd|pass) ?= ?['\"](?!(['\"]))",
      "caption": "static passwords",
      "description": None
  },
  {
      "part": "contents",
      "type": "regex",
      "pattern": "(\\.(verizon|edgecast|uplynk).*\\.(net|com):(?!(80|443)\b))",
      "caption": "Verizon/EdgeCast/Uplynk host names on non-http ports",
      "description": None
  },
  {
    "part": "filename",
    "type": "regex",
    "pattern": "\\A.*_rsa\\z",
    "caption": "Private SSH key",
    "description": None
  },
  {
    "part": "filename",
    "type": "regex",
    "pattern": "\\A.*_dsa\\z",
    "caption": "Private SSH key",
    "description": None
  },
  {
    "part": "filename",
    "type": "regex",
    "pattern": "\\A.*_ed25519\\z",
    "caption": "Private SSH key",
    "description": None
  },
  {
    "part": "filename",
    "type": "regex",
    "pattern": "\\A.*_ecdsa\\z",
    "caption": "Private SSH key",
    "description": None
  },
  {
    "part": "path",
    "type": "regex",
    "pattern": "\\.?ssh/config\\z",
    "caption": "SSH configuration file",
    "description": None
  },
  {
    "part": "extension",
    "type": "match",
    "pattern": "pem",
    "caption": "Potential cryptographic private key",
    "description": None
  },
  {
    "part": "extension",
    "type": "regex",
    "pattern": "\\Akey(pair)?\\z",
    "caption": "Potential cryptographic private key",
    "description": None
  },
  {
    "part": "extension",
    "type": "match",
    "pattern": "pkcs12",
    "caption": "Potential cryptographic key bundle",
    "description": None
  },
  {
    "part": "extension",
    "type": "match",
    "pattern": "pfx",
    "caption": "Potential cryptographic key bundle",
    "description": None
  },
  {
    "part": "extension",
    "type": "match",
    "pattern": "p12",
    "caption": "Potential cryptographic key bundle",
    "description": None
  },
  {
    "part": "extension",
    "type": "match",
    "pattern": "asc",
    "caption": "Potential cryptographic key bundle",
    "description": None
  },
  {
    "part": "filename",
    "type": "match",
    "pattern": "otr.private_key",
    "caption": "Pidgin OTR private key",
    "description": None
  },
  {
    "part": "filename",
    "type": "regex",
    "pattern": "\\A\\.?(bash_|zsh_|z)?history\\z",
    "caption": "Shell command history file",
    "description": None
  },
  {
    "part": "filename",
    "type": "regex",
    "pattern": "\\A\\.?mysql_history\\z",
    "caption": "MySQL client command history file",
    "description": None
  },
  {
    "part": "filename",
    "type": "regex",
    "pattern": "\\A\\.?psql_history\\z",
    "caption": "PostgreSQL client command history file",
    "description": None
  },
  {
    "part": "filename",
    "type": "regex",
    "pattern": "\\A\\.?pgpass\\z",
    "caption": "PostgreSQL password file",
    "description": None
  },
  {
    "part": "filename",
    "type": "regex",
    "pattern": "\\A\\.?irb_history\\z",
    "caption": "Ruby IRB console history file",
    "description": None
  },
  {
    "part": "path",
    "type": "regex",
    "pattern": "\\.?purple\\/accounts\\.xml\\z",
    "caption": "Pidgin chat client account configuration file",
    "description": None
  },
  {
    "part": "path",
    "type": "regex",
    "pattern": "\\.?xchat2?\\/servlist_?\\.conf\\z",
    "caption": "Hexchat/XChat IRC client server list configuration file",
    "description": None
  },
  {
    "part": "path",
    "type": "regex",
    "pattern": "\\.?irssi\\/config\\z",
    "caption": "Irssi IRC client configuration file",
    "description": None
  },
  {
    "part": "path",
    "type": "regex",
    "pattern": "\\.?recon-ng\\/keys\\.db\\z",
    "caption": "Recon-ng web reconnaissance framework API key database",
    "description": None
  },
  {
    "part": "filename",
    "type": "regex",
    "pattern": "\\A\\.?dbeaver-data-sources.xml\\z",
    "caption": "DBeaver SQL database manager configuration file",
    "description": None
  },
  {
    "part": "filename",
    "type": "regex",
    "pattern": "\\A\\.?muttrc\\z",
    "caption": "Mutt e-mail client configuration file",
    "description": None
  },
  {
    "part": "filename",
    "type": "regex",
    "pattern": "\\A\\.?s3cfg\\z",
    "caption": "S3cmd configuration file",
    "description": None
  },
  {
    "part": "path",
    "type": "regex",
    "pattern": "\\.?aws/credentials\\z",
    "caption": "AWS CLI credentials file",
    "description": None
  },
  {
    "part": "filename",
    "type": "regex",
    "pattern": "\\A\\.?trc\\z",
    "caption": "T command-line Twitter client configuration file",
    "description": None
  },
  {
    "part": "extension",
    "type": "match",
    "pattern": "ovpn",
    "caption": "OpenVPN client configuration file",
    "description": None
  },
  {
    "part": "filename",
    "type": "regex",
    "pattern": "\\A\\.?gitrobrc\\z",
    "caption": "Well, this is awkward... Gitrob configuration file",
    "description": None
  },
  {
    "part": "filename",
    "type": "regex",
    "pattern": "\\A\\.?(bash|zsh)rc\\z",
    "caption": "Shell configuration file",
    "description": "Shell configuration files might contain information such as server hostnames, passwords and API keys."
  },
  {
    "part": "filename",
    "type": "regex",
    "pattern": "\\A\\.?(bash_|zsh_)?profile\\z",
    "caption": "Shell profile configuration file",
    "description": "Shell configuration files might contain information such as server hostnames, passwords and API keys."
  },
  {
    "part": "filename",
    "type": "regex",
    "pattern": "\\A\\.?(bash_|zsh_)?aliases\\z",
    "caption": "Shell command alias configuration file",
    "description": "Shell configuration files might contain information such as server hostnames, passwords and API keys."
  },
  {
    "part": "filename",
    "type": "match",
    "pattern": "secret_token.rb",
    "caption": "Ruby On Rails secret token configuration file",
    "description": "If the Rails secret token is known, it can allow for remote code execution. (http://www.exploit-db.com/exploits/27527/)"
  },
  {
    "part": "filename",
    "type": "match",
    "pattern": "omniauth.rb",
    "caption": "OmniAuth configuration file",
    "description": "The OmniAuth configuration file might contain client application secrets."
  },
  {
    "part": "filename",
    "type": "match",
    "pattern": "carrierwave.rb",
    "caption": "Carrierwave configuration file",
    "description": "Can contain credentials for online storage systems such as Amazon S3 and Google Storage."
  },
  {
    "part": "filename",
    "type": "match",
    "pattern": "schema.rb",
    "caption": "Ruby On Rails database schema file",
    "description": "Contains information on the database schema of a Ruby On Rails application."
  },
  {
    "part": "filename",
    "type": "match",
    "pattern": "database.yml",
    "caption": "Potential Ruby On Rails database configuration file",
    "description": "Might contain database credentials."
  },
  {
    "part": "filename",
    "type": "match",
    "pattern": "settings.py",
    "caption": "Django configuration file",
    "description": "Might contain database credentials, online storage system credentials, secret keys, etc."
  },
  {
    "part": "filename",
    "type": "regex",
    "pattern": "\\A(.*)?config(\\.inc)?\\.php\\z",
    "caption": "PHP configuration file",
    "description": "Might contain credentials and keys."
  },
  {
    "part": "extension",
    "type": "match",
    "pattern": "kdb",
    "caption": "KeePass password manager database file",
    "description": None
  },
  {
    "part": "extension",
    "type": "match",
    "pattern": "agilekeychain",
    "caption": "1Password password manager database file",
    "description": None
  },
  {
    "part": "extension",
    "type": "match",
    "pattern": "keychain",
    "caption": "Apple Keychain database file",
    "description": None
  },
  {
    "part": "extension",
    "type": "regex",
    "pattern": "\\Akey(store|ring)\\z",
    "caption": "GNOME Keyring database file",
    "description": None
  },
  {
    "part": "extension",
    "type": "match",
    "pattern": "log",
    "caption": "Log file",
    "description": "Log files might contain information such as references to secret HTTP endpoints, session IDs, user information, passwords and API keys."
  },
  {
    "part": "extension",
    "type": "match",
    "pattern": "pcap",
    "caption": "Network traffic capture file",
    "description": None
  },
  {
    "part": "extension",
    "type": "regex",
    "pattern": "\\Asql(dump)?\\z",
    "caption": "SQL dump file",
    "description": None
  },
  {
    "part": "extension",
    "type": "match",
    "pattern": "gnucash",
    "caption": "GnuCash database file",
    "description": None
  },
  {
    "part": "filename",
    "type": "regex",
    "pattern": "backup",
    "caption": "Contains word: backup",
    "description": None
  },
  {
    "part": "filename",
    "type": "regex",
    "pattern": "dump",
    "caption": "Contains word: dump",
    "description": None
  },
  {
    "part": "filename",
    "type": "regex",
    "pattern": "password",
    "caption": "Contains word: password",
    "description": None
  },
  {
    "part": "filename",
    "type": "regex",
    "pattern": "credential",
    "caption": "Contains word: credential",
    "description": None
  },
  {
    "part": "filename",
    "type": "regex",
    "pattern": "secret",
    "caption": "Contains word: secret",
    "description": None
  },
  {
    "part": "filename",
    "type": "regex",
    "pattern": "private.*key",
    "caption": "Contains words: private, key",
    "description": None
  },
  {
    "part": "filename",
    "type": "match",
    "pattern": "jenkins.plugins.publish_over_ssh.BapSshPublisherPlugin.xml",
    "caption": "Jenkins publish over SSH plugin file",
    "description": None
  },
  {
    "part": "filename",
    "type": "match",
    "pattern": "credentials.xml",
    "caption": "Potential Jenkins credentials file",
    "description": None
  },
  {
    "part": "filename",
    "type": "regex",
    "pattern": "\\A\\.?htpasswd\\z",
    "caption": "Apache htpasswd file",
    "description": None
  },
  {
    "part": "filename",
    "type": "regex",
    "pattern": "\\A(\\.|_)?netrc\\z",
    "caption": "Configuration file for auto-login process",
    "description": "Might contain username and password."
  },
  {
    "part": "extension",
    "type": "match",
    "pattern": "kwallet",
    "caption": "KDE Wallet Manager database file",
    "description": None
  },
  {
    "part": "filename",
    "type": "match",
    "pattern": "LocalSettings.php",
    "caption": "Potential MediaWiki configuration file",
    "description": None
  },
  {
    "part": "extension",
    "type": "match",
    "pattern": "tblk",
    "caption": "Tunnelblick VPN configuration file",
    "description": None
  },
  {
    "part": "path",
    "type": "regex",
    "pattern": "\\.?gem/credentials\\z",
    "caption": "Rubygems credentials file",
    "description": "Might contain API key for a rubygems.org account."
  },
  {
    "part": "filename",
    "type": "match",
    "pattern": "Favorites.plist",
    "caption": "Sequel Pro MySQL database manager bookmark file",
    "description": None
  },
  {
    "part": "filename",
    "type": "match",
    "pattern": "configuration.user.xpl",
    "caption": "Little Snitch firewall configuration file",
    "description": "Contains traffic rules for applications"
  },
  {
    "part": "extension",
    "type": "match",
    "pattern": "dayone",
    "caption": "Day One journal file",
    "description": None
  },
  {
    "part": "filename",
    "type": "match",
    "pattern": "journal.txt",
    "caption": "Potential jrnl journal file",
    "description": None
  },
  {
    "part": "filename",
    "type": "regex",
    "pattern": "\\A\\.?tugboat\\z",
    "caption": "Tugboat DigitalOcean management tool configuration",
    "description": None
  },
  {
    "part": "filename",
    "type": "regex",
    "pattern": "\\A\\.?git-credentials\\z",
    "caption": "git-credential-store helper credentials file",
    "description": None
  },
  {
    "part": "filename",
    "type": "regex",
    "pattern": "\\A\\.?gitconfig\\z",
    "caption": "Git configuration file",
    "description": None
  },
  {
    "part": "filename",
    "type": "match",
    "pattern": "knife.rb",
    "caption": "Chef Knife configuration file",
    "description": "Might contain references to Chef servers"
  },
  {
    "part": "path",
    "type": "regex",
    "pattern": "\\.?chef/(.*)\\.pem\\z",
    "caption": "Chef private key",
    "description": "Can be used to authenticate against Chef servers"
  },
  {
    "part": "filename",
    "type": "match",
    "pattern": "proftpdpasswd",
    "caption": "cPanel backup ProFTPd credentials file",
    "description": "Contains usernames and password hashes for FTP accounts"
  },
  {
    "part": "filename",
    "type": "match",
    "pattern": "robomongo.json",
    "caption": "Robomongo MongoDB manager configuration file",
    "description": "Might contain credentials for MongoDB databases"
  },
  {
    "part": "filename",
    "type": "match",
    "pattern": "filezilla.xml",
    "caption": "FileZilla FTP configuration file",
    "description": "Might contain credentials for FTP servers"
  },
  {
    "part": "filename",
    "type": "match",
    "pattern": "recentservers.xml",
    "caption": "FileZilla FTP recent servers file",
    "description": "Might contain credentials for FTP servers"
  },
  {
    "part": "filename",
    "type": "match",
    "pattern": "ventrilo_srv.ini",
    "caption": "Ventrilo server configuration file",
    "description": "Might contain passwords"
  },
  {
    "part": "filename",
    "type": "regex",
    "pattern": "\\A\\.?dockercfg\\z",
    "caption": "Docker configuration file",
    "description": "Might contain credentials for public or private Docker registries"
  },
  {
    "part": "filename",
    "type": "regex",
    "pattern": "\\A\\.?npmrc\\z",
    "caption": "NPM configuration file",
    "description": "Might contain credentials for NPM registries"
  },
  {
    "part": "filename",
    "type": "match",
    "pattern": "terraform.tfvars",
    "caption": "Terraform variable config file",
    "description": "Might contain credentials for terraform providers"
  },
  {
    "part": "filename",
    "type": "regex",
    "pattern": "\\A\\.?env\\z",
    "caption": "Environment configuration file",
    "description": None
  }
]

parser = argparse.ArgumentParser(description="pre-receive oopsy checker",
                                 formatter_class=argparse.RawTextHelpFormatter)
parser.add_argument('PATH', type=str,
                    help='The directory to analyze')
parser.add_argument('--first', action='store_true',
                    help='Exit on the first file that violates our rules')
parser.add_argument('--match', action='store_true',
                    help='Print the matching value')
parser.add_argument('--verbose', action='store_true',
                    help='Be noisy.  Implies --match')
parser.add_argument('--json', action='store_true',
                    help='Produce JSON output.  Overrides --verbose')
args = parser.parse_args()

if args.verbose:
    args.match = True


def verbose(a_string):
    if args.verbose:
        print a_string

# /// \brief   perform a match
# /// \details
# /// \return  The data that matched if it dide
# ///          None if no matches
# /// \param   a_data  The data to match against
# /// \param   a_pattern The pattern to run
# /// \param   a_type 'regex' or 'match' to regex or exact match data with pattern
def do_match(a_data, a_pattern, a_type):

    if a_type == "regex":
        match = re.compile(a_pattern, re.IGNORECASE).search(a_data)
        if match:
            return a_data.strip()
    elif a_type == "match":
        if a_data == a_pattern:
            return a_data
    else:
        print "Invalid type provided: '%s'."
    return None



# /// \brief   analyze a file
# /// \details
# /// \return  A list of the pattern violations from that file
# /// \param   a_path     The file path to analyze
def get_file_violations(a_subdir, a_filename):

    violations = []

    # for each object in the array
    for signature in signatures:
        #print signature

        l_data = ""
        if signature['part'] == "contents":

            l_contents = ""
            try:
                with open(os.path.join(a_subdir, a_filename), 'r') as content_file:
                    l_contents = content_file.readlines()
            except IOError, e:
                pass

            for l_data in l_contents:
                l_violations = do_match(l_data, signature['pattern'], signature['type'])
                if l_violations:
                    violations.append({ "data": l_violations, "signature": signature} )

        else:

            if signature['part'] == "filename":
                l_data = a_filename
            elif signature['part'] == "extension":
                l_data = os.path.splitext(a_filename)[1][1:]
            elif signature['part'] == "path":
                l_data = os.path.join(a_subdir, a_filename)
            else:
                print "Unknown part: '%s'" % signature['part']

            l_violations = do_match(l_data, signature['pattern'], signature['type'])
            if l_violations:
                violations.append({ "data": l_violations, "signature": signature} )

    return violations


# /// \brief   analyze a file
# /// \details
# /// \return  A list of the pattern violations from that file
# /// \param   a_path     The file path to analyze
def get_violations(a_path):

    violations = {}
    for subdir, dirs, files in os.walk(a_path):
        if "/.git" in subdir:
            continue
        for file in files:
            verbose("Analyzing %s..." % (os.path.join(subdir, file)))
            l_violations = get_file_violations(subdir, file)
            if l_violations:
                violations[os.path.join(subdir, file)] = l_violations
                if args.first:
                    return violations
    return violations

# walk the entire path
violations = get_violations(args.PATH)

if args.json:
    print json.dumps(violations)
else:
    for k,v in violations.iteritems():
        for v_details in v:
            #print k,v_details
            if args.match:
                print "%s has %s %s matches pattern: %s -> %s" % (k, v_details["signature"]["caption"], v_details["signature"]["part"], v_details["signature"]["pattern"], v_details["data"])
            else:
                print "%s has %s %s" % (k, v_details["signature"]["caption"], v_details["signature"]["part"])
